### ISSUE TITLE
Z3: Komentari

### ISSUE THREAD

**Issue by zbetmen1** [bataVeljko/Informacioni-sistem-poljoprivredne-zadruge#1]
1. Bilo bi dobro da se dijagram konteksta i dijagrami tokova podataka prebace u prvo poglavlje. 
2. Slika 4: Jedva se čitaju nazivi slučajeva upotrebe
3. Slika 6: "Kooperant" --> "Korisnik"? Nema potrebe navoditi aktera u nazivu aktivnosti (Za to služe linije sutora). Postoji oznaka za čekanje koja bi trebalo da zameni aktivnost "Čekaj 7 dana". Pogledajte: http://poincare.matf.bg.ac.rs/~asimic/2017/is/9/Cas9_Resenje.pdf (strana 8).
4. SLučaj upotrebe "Apliciranje za članstvo u zadruzu": mnogo se meša "Korisnik" i "Kooperant". U spisku aktera je naveden "Kooperant", a u glavnom toku svuda piše "Korisnik". Treba ovo srediti jer je zbunjujuće. Pogledajte i u ostalim slučajevima upotrebe. U koraku 7 umesto "Korisnik se obaveštava..." treba "Sistem obaveštava korisnika..."
5. "Istupanje iz zadruge": slično kao u prethodnom, akter je "Član zadruge", a u glavnom toku je svuda naveden "Korisnik".
6. "Izbacivanje iz zadruge": "Član zadruge je obisan iz sistema" --> "Sistem briše člana zadruge", "Korisnik dobija automatsku poruku...." --> "Sistem šalje poruku korisniku...". Dakle svaki korak glavnog toka mora da bude u aktivu. 
7. Slika 8 i slika 9 prikazuju istu stvar
8. Slika 10: Grananje se drugacije prikazuje na diagramu aktivnosti
9. Slika 11: "AzurirajStanje" se dešava samo u prvom slučaju. Po diagramu izgleda da se stanje ažurira i nakon žalbe
10. Slika 12 i slika 13 prikazuju istu stvar isto vazi za slike 15 i 16
11. Slika 14: Član se prijavljuje za dostavu, povratna grana bi trebalo da ide od zaposlenog do člana i da bude npr. "prihvatiPrijavuZaDostavu()", a obrisiObavestenje treba da bude nova poruka koja se šalje sistemu. "proveriDostupneProizvode" je akcija koju zaposleni radi samostalno (dakle strelica ide od Zaposlenog ka Zaposlenom), a povratna poruka treba da bude npr, "potvrdiDostavu" 
i da ide ka Članu.

**Comment by zokaaagajich** [comment]
Ispravljene sve sugestije
