### ISSUE TITLE
Finalna verzija

### ISSUE THREAD

**Issue by zbetmen1** [bataVeljko/Informacioni-sistem-poljoprivredne-zadruge#2]
- U delu gde je baza podataka pise "U ovom delu bice data shema predlozene baze podataka, kao i opis entiteta ...", a nigde nema opisa entiteta. Ili ga dodajte ili promenite ovu recenicu. 
- Nedostaje zakljucak i literatura (reference)

**Comment by zokaaagajich** [comment]
Dodat zakljucak i literatura.
